#!/bin/bash
#
# epoch cat
# find epoch time and convert to std time format
#

while read line 
do

time=$(echo "$line" | egrep -o "^\[[0-9]*\]" | tr "[]" "x")
time=${time//x}
newtime="$(date '+%F %T' --date=@$time)"

echo "$line" | sed "s/$time/$newtime/g"
done

